[package]
name = "dekerakt-hub"
version = "0.1.0"
authors = [
  "LeshaInc <includeurl@gmail.com>",
  "Alexander (Fingercomp) <binbin226@gmail.com>"
]

[dependencies]
mio = "0.6"

slog = "1.4"
slog-scope = "0.2"
slog-term = "1.3"

argparse = "0.2"
unicode-width = "0.1"

linked-hash-map = "0.4"
